# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("hello.proto", :syntax => :proto3) do
    add_message "hello.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "hello.HelloResponse" do
      optional :greeting, :string, 1
    end
  end
end

module Hello
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloRequest").msgclass
  HelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloResponse").msgclass
end
